global using Xunit;
global using FluentAssertions;
global using Moq;
global using OrderService.Domain.Entities;
global using OrderService.Domain.ValueObjects;
global using OrderService.Domain.Exceptions;
global using OrderService.Domain.Enums;
global using OrderService.Application.DTOs;
global using OrderService.Application.Abstractions;
